Unify version pattern, allow local dandiset URLs
dandi/dandischema pull request #121
Opened 2022-03-04 18:02 UTC by AlmightyYakob

When doing work in the API, I noticed that the regex pattern for the published dandiset URL was hardcoded to `https://dandiarchive.org`. I thought this should be prod/dev agnostic, as the other URL patterns are.

Also, I noticed there was some duplication regarding version patterns, so I unified them.

2022-03-04 19:30 UTC, satra commented
@jwodder - can you please confirm that the CLI test failures are known issues at this point in time ?

2022-03-04 19:33 UTC, jwodder commented
@satra They are not.  I see messages like `'https://dandiarchive.org/dandiset/000002/0.220304.1811' does not match '^http://localhost(:\\\\d+)?/dandiset/\\\\d{6}/\\\\d+\\\\.\\\\d+\\\\.\\\\d+$'`, which are clearly caused by this PR.

@AlmightyYakob If `DANDI_ALLOW_LOCALHOST_URLS` is set, then `DANDI_ARCHIVE_PATTERN` should allow localhost *in addition* to https://dandiarchive.org.

2022-03-04 20:59 UTC, jwodder requested changes

2022-03-04 20:59 UTC, jwodder commented on dandischema/models.py
> +    DANDI_ARCHIVE_PATTERN = r"(https://dandiarchive.org)|(http://localhost)(:\d+)?"
```suggestion
    DANDI_ARCHIVE_PATTERN = r"(https://dandiarchive.org|http://localhost(:\d+)?)"
```

2022-03-07 17:35 UTC, AlmightyYakob commented
@jwodder are these failing codecov tests a problem?

2022-03-07 17:39 UTC, jwodder commented
@AlmightyYakob No.

2022-03-07 17:42 UTC, merged